# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_sumo_wrappers", use_symbols = TRUE, package_name = "sumo")

#' @docType sumo-package
"_PACKAGE"
#' @usage NULL
#' @useDynLib sumo, .registration = TRUE
NULL

#' Factors of a number new
#' @export
#' @param input The number to calculate the factors of.
factors <- function(input, include_original) .Call(wrap__factors, input, include_original)

#' Digital sum of a number
#' @export
#' @param n The number to calculate the digital sum of.
digital_sum <- function(n) .Call(wrap__digital_sum, n)

#' Area of a polyon new
#' @export
#' @param x The x-coordinates of the polygon.
#' @param y The y-coordinates of the polygon.
polygon_area <- function(x, y) .Call(wrap__polygon_area, x, y)

#' Replace all text after a given character
#' @export
#' @param string The string to replace in.
#' @param symbol The symbol to find in \code{string}
#' @param replacement The replacement of \code{string} before \code{symbol}.
replace_after <- function(string, symbol, replacement) .Call(wrap__replace_after, string, symbol, replacement)

#' Replace all text before a given character
#' @export
#' @param string The string to replace in.
#' @param symbol The symbol to find in \code{string}
#' @param replacement The replacement of \code{string} before \code{symbol}.
replace_before <- function(string, symbol, replacement) .Call(wrap__replace_before, string, symbol, replacement)


# nolint end
