# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_sumo_wrappers", use_symbols = TRUE, package_name = "sumo")

#' @docType package
#' @usage NULL
#' @useDynLib sumo, .registration = TRUE
NULL

#' Factors of a number new
#' @export
factors <- function(input, include_original) .Call(wrap__factors, input, include_original)

#' Digital sum of a number
#' @export
digital_sum <- function(n) .Call(wrap__digital_sum, n)

#' Area of a polyon new
#' @export
polygon_area <- function(x, y) .Call(wrap__polygon_area, x, y)

#' Replace all text after a given character
#' @export
replace_after <- function(string, symbol, replacement) .Call(wrap__replace_after, string, symbol, replacement)

#' Replace all text before a given character
#' @export
replace_before <- function(string, symbol, replacement) .Call(wrap__replace_before, string, symbol, replacement)


# nolint end
